import json
import zipfile
import os
import random
import argparse
from datetime import datetime

def load_team_payouts(file_path):
    """Loads payout structures from the team's JSON format."""
    with open(file_path, 'r') as f:
        data = json.load(f)
    # Extract just the prize percentages/values from the first structure
    prizes = data['structures'][0]['prizes']
    # Convert dict to sorted list of values
    return [prizes[str(i)] for i in range(1, len(prizes) + 1)]

def generate_hand_config(title, stacks, blinds, payouts, script_content=None, model="ICM"):
    """
    Generates the HRC settings.json dictionary.
    """
    players = []
    for i, stack in enumerate(stacks):
        players.append({
            "name": f"Player {i+1}",
            "stack": stack,
            "bounty": 0
        })

    config = {
        "version": 1,
        "hand": {
            "title": title,
            "description": "Generated by HRC Automation",
            "date": datetime.utcnow().isoformat() + "Z",
            "format": "NLHE",
            "model": model,
            "payouts": payouts,
            "chipsInPlay": sum(stacks),
            "blinds": {
                "smallBlind": blinds["sb"],
                "bigBlind": blinds["bb"],
                "ante": blinds["ante"]
            },
            "players": players
        },
        "treeConfig": {
            "maxActivePlayers": len(stacks),
            "allowFlats": True,
            "preflopSizings": "2.5bb, 3bet:9bb, allin",
            "postflop": {
                "enabled": False
            }
        }
    }
    
    # If a custom script is provided, we attach it to the treeConfig
    if script_content:
        config["treeConfig"]["type"] = "SCRIPT"
        config["treeConfig"]["script"] = script_content
        
    return config

def package_hrcz(config, output_path):
    """
    Writes the config to settings.json and zips it into an .hrcz file.
    """
    temp_json = "settings.json"
    with open(temp_json, "w") as f:
        json.dump(config, f, indent=2)
    
    with zipfile.ZipFile(output_path, "w") as z:
        z.write(temp_json)
    
    os.remove(temp_json)

def main():
    parser = argparse.ArgumentParser(description="HRC Hand Generator with Team Assets")
    parser.add_argument("--count", type=int, default=1, help="Number of hands to generate")
    parser.add_argument("--outdir", type=str, default="output_hands", help="Output directory")
    parser.add_argument("--script", type=str, help="Path to the team JS script (e.g., high_icm_test.js)")
    parser.add_argument("--payouts", type=str, help="Path to the team payout JSON (e.g., mtt_300_players.json)")
    args = parser.parse_args()

    if not os.path.exists(args.outdir):
        os.makedirs(args.outdir)

    # Load script content if provided
    script_content = None
    if args.script and os.path.exists(args.script):
        with open(args.script, 'r') as f:
            script_content = f.read()

    # Load payouts if provided
    payout_values = [50, 30, 20] # Default
    if args.payouts and os.path.exists(args.payouts):
        payout_values = load_team_payouts(args.payouts)

    # Common blind levels (SB, BB, Ante)
    blind_levels = [
        (100, 200, 25), (150, 300, 40), (200, 400, 50),
        (300, 600, 75), (400, 800, 100), (500, 1000, 125),
        (600, 1200, 150), (800, 1600, 200), (1000, 2000, 250)
    ]

    for i in range(args.count):
        # Requirements: 8 players and unique stack sizes
        num_players = 8 
        
        # Randomly select a blind level
        sb, bb, ante = random.choice(blind_levels)
        
        # Generate unique stacks between 10bb and 100bb
        # Using random.sample to ensure no duplicates within the hand
        stack_options = list(range(10 * bb, 100 * bb, 100)) # 100-chip increments
        if len(stack_options) < num_players:
             stack_options = list(range(10 * bb, 100 * bb))
                    
        stacks = random.sample(stack_options, num_players)
        
        blinds = {"sb": sb, "bb": bb, "ante": ante}
        config = generate_hand_config(f"Hand {i+1} (BB:{bb})", stacks, blinds, payout_values, script_content=script_content)
        
        filename = f"hand_{i+1}.hrcz"
        output_path = os.path.join(args.outdir, filename)
        package_hrcz(config, output_path)
        print(f"Generated {output_path}")

if __name__ == "__main__":
    main()
