import json
import zipfile
import os
import random
import argparse
from datetime import datetime, timezone

def load_team_payouts(file_path):
    """Loads payout structures from the team's JSON format."""
    with open(file_path, 'r') as f:
        data = json.load(f)
    prizes = data['structures'][0]['prizes']
    return [float(prizes[str(i)]) for i in range(1, len(prizes) + 1)]

def generate_hand_config(title, stacks, blinds, payouts, script_content=None, model="ICM"):
    """
    Generates a standard HRC settings.json dictionary.
    """
    players = []
    for i, stack in enumerate(stacks):
        players.append({
            "name": f"Player {i+1}",
            "stack": int(stack),
            "bounty": 0.0
        })

    config = {
        "version": 1,
        "hand": {
            "title": title,
            "description": "Generated by HRC Automation",
            "date": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
            "format": "NLHE",
            "model": model,
            "payouts": payouts,
            "blinds": {
                "sb": int(blinds["sb"]),
                "bb": int(blinds["bb"]),
                "ante": int(blinds["ante"]),
                "anteType": "REGULAR"
            },
            "players": players
        },
        "treeConfig": {
            "maxActivePlayers": len(stacks),
            "allowFlats": True,
            "preflopSizings": "2.5bb, 3bet:9bb, allin",
            "postflop": {
                "enabled": False
            }
        }
    }
    
    if script_content:
        config["treeConfig"]["type"] = "SCRIPT"
        config["treeConfig"]["script"] = script_content
        
    return config

def package_hrcz(config, output_path):
    """
    Writes the config to settings.json and zips it into an .hrcz file.
    """
    temp_json = "settings.json"
    with open(temp_json, "w") as f:
        json.dump(config, f, indent=2)
    
    with zipfile.ZipFile(output_path, "w") as z:
        z.write(temp_json)
    
    os.remove(temp_json)

def main():
    parser = argparse.ArgumentParser(description="HRC Hand Generator (Standard Schema)")
    parser.add_argument("--count", type=int, default=1, help="Number of hands to generate")
    parser.add_argument("--outdir", type=str, default="output_hands", help="Output directory")
    parser.add_argument("--script", type=str, help="Path to the team JS script")
    parser.add_argument("--payouts", type=str, help="Path to the team payout JSON")
    args = parser.parse_args()

    if not os.path.exists(args.outdir):
        os.makedirs(args.outdir)

    script_content = None
    if args.script and os.path.exists(args.script):
        with open(args.script, 'r') as f:
            script_content = f.read()

    # Default payouts
    payout_values = [50.0, 30.0, 20.0]
    if args.payouts and os.path.exists(args.payouts):
        payout_values = load_team_payouts(args.payouts)

    blind_levels = [
        (100, 200, 25), (200, 400, 50), (400, 800, 100), (1000, 2000, 250)
    ]

    for i in range(args.count):
        num_players = 8 
        sb, bb, ante = random.choice(blind_levels)
        
        stack_options = list(range(10 * bb, 100 * bb, 100))
        stacks = random.sample(stack_options, num_players)
        
        blinds = {"sb": sb, "bb": bb, "ante": ante}
        config = generate_hand_config(f"Hand {i+1}", stacks, blinds, payout_values, script_content=script_content)
        
        filename = f"hand_{i+1}.hrcz"
        output_path = os.path.join(args.outdir, filename)
        package_hrcz(config, output_path)
        print(f"Generated {output_path}")

if __name__ == "__main__":
    main()
